/**
 * RecruitFlow's portable design-system contract.
 *
 * CSS custom properties in `apps/web/src/styles/tokens.css` remain the runtime
 * source of truth. This object gives workspace packages a stable, serializable
 * description of the same semantic roles without coupling them to Tailwind.
 */
export const designTokens = {
  name: 'RecruitFlow',
  version: '1.1.0',
  colorModes: ['light', 'dark'],
  colors: {
    primary: '#1d4ed8',
    background: '#f8fafc',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    surfaceSubtle: '#f8f9fb',
    surfaceMuted: '#f1f5f9',
    surfaceHover: '#f4f6f8',
    surfaceSelected: '#e6f4fb',
    text: '#0f172a',
    ink950: '#0f172a',
    ink800: '#1e293b',
    ink700: '#334155',
    ink500: '#475569',
    ink400: '#64748b',
    muted: '#475569',
    border: '#cbd5e1',
    borderSubtle: '#eceff3',
    borderStrong: '#9ca3af',
    action: '#1d4ed8',
    actionSecondary: '#2563eb',
    actionStrong: '#1e40af',
    actionSoft: 'rgba(29, 78, 216, 0.10)',
    // Neon accents
    neonCyan: '#22d3ee',
    neonViolet: '#7c3aed',
    // Status tones
    success: '#15803d',
    successSoft: '#e8faf2',
    warning: '#b45309',
    warningSoft: '#fff7e8',
    danger: '#b91c1c',
    dangerSoft: '#fff0f1',
    info: '#0369a1',
    infoSoft: '#e6f4fb',
  },
  darkColors: {
    primary: '#3b82f6',
    background: '#0f172a',
    surface: '#111827',
    surfaceElevated: '#1e293b',
    surfaceSubtle: '#0b1020',
    surfaceMuted: '#1e293b',
    text: '#f8fafc',
    ink950: '#f8fafc',
    ink800: '#e2e8f0',
    ink700: '#cbd5e1',
    ink500: '#9ca3af',
    ink400: '#64748b',
    muted: '#9ca3af',
    border: '#374151',
    borderSubtle: '#1e293b',
    borderStrong: '#4b5563',
    neonCyan: '#38bdf8',
    neonViolet: '#a78bfa',
    success: '#22c55e',
    warning: '#f59e0b',
    danger: '#ef4444',
    info: '#38bdf8',
  },
  cssVariables: {
    // Core surface and color tokens
    canvas: '--color-canvas',
    surface: '--color-surface',
    surfaceElevated: '--color-surface-elevated',
    surfaceSubtle: '--color-surface-subtle',
    surfaceMuted: '--color-surface-muted',
    surfaceHover: '--color-surface-hover',
    surfaceSelected: '--color-surface-selected',
    border: '--color-border',
    borderSubtle: '--color-border-subtle',
    borderStrong: '--color-border-strong',
    text: '--color-ink-950',
    text800: '--color-ink-800',
    text700: '--color-ink-700',
    text500: '--color-ink-500',
    text400: '--color-ink-400',
    action: '--color-action',
    focusRing: '--focus-ring',
    // Neon accents
    neonCyan: '--color-neon-cyan',
    neonViolet: '--color-neon-violet',
    // Semantic palettes
    success: '--color-success',
    successSoft: '--color-success-soft',
    warning: '--color-warning',
    warningSoft: '--color-warning-soft',
    danger: '--color-danger',
    dangerSoft: '--color-danger-soft',
    info: '--color-info',
    infoSoft: '--color-info-soft',
  },

  spacing: [4, 8, 12, 16, 20, 24, 32, 40, 48],
  radius: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    full: 9999,
  },
  motion: {
    instant: 100,
    fast: 150,
    standard: 200,
    slow: 300,
  },
  breakpoints: {
    xs: 375,
    sm: 430,
    md: 768,
    lg: 1024,
    xl: 1280,
    xxl: 1440,
  },
  shadows: {
    none: 'none',
    popover: '0 4px 12px -2px rgb(16 24 40 / 0.08), 0 2px 4px -2px rgb(16 24 40 / 0.04)',
    modal: '0 8px 24px -4px rgb(16 24 40 / 0.12), 0 4px 8px -2px rgb(16 24 40 / 0.06)',
    drawer: '0 12px 32px -4px rgb(16 24 40 / 0.14)',
  },
} as const;

export const componentFamilies = {
  actions: ['Button', 'IconButton'],
  dataEntry: ['Input', 'Select', 'Textarea', 'CheckboxField', 'FormField', 'FormSection'],
  navigation: ['Tabs', 'Pagination', 'DataToolbar'],
  feedback: ['Alert', 'Toast', 'PageState', 'Skeleton'],
  surfaces: ['Card', 'MetricCard', 'SpotlightCard', 'SectionHeader'],
  dataDisplay: ['Badge', 'StatusBadge', 'Avatar', 'DataTable', 'ResponsiveDataView', 'DetailSummary', 'ProgressBar'],
  workflow: ['ActivityTimeline', 'PipelineStepper', 'PipelineBoard', 'Scorecard'],
  overlays: ['Modal', 'ConfirmDialog', 'Drawer'],
} as const;

export type DesignTokenContract = typeof designTokens;
export type ComponentFamily = keyof typeof componentFamilies;
