-- Phase 11: Self-service profile and preferences
-- Forward-only migration. Never edit or revert an applied migration.

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "theme" VARCHAR(10) NOT NULL DEFAULT 'light',
  ADD COLUMN IF NOT EXISTS "timezone" VARCHAR(80) NOT NULL DEFAULT 'UTC',
  ADD COLUMN IF NOT EXISTS "dateFormat" VARCHAR(40) NOT NULL DEFAULT 'MMM d, yyyy',
  ADD COLUMN IF NOT EXISTS "timeFormat" VARCHAR(10) NOT NULL DEFAULT '12h',
  ADD COLUMN IF NOT EXISTS "reducedMotion" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "inAppNotifications" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "emailNotifications" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "interviewReminders" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "approvalReminders" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "taskReminders" BOOLEAN NOT NULL DEFAULT TRUE;
